// <copyright file="Program.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace API_template
{
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Hosting;

    /// <summary>
    /// Program generated by api template.
    /// </summary>
    public class Program
    {
        /// <summary>
        /// main.
        /// </summary>
        /// <param name="args">template generated, unknown currently.</param>
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        /// <summary>
        /// configures web builder using the startup file.
        /// </summary>
        /// <param name="args"> template generated, unknown currently.</param>
        /// <returns>the startup settings for the api.</returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
